import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";

import { Noto_Sans } from "next/font/google"

const noto_sansFont= Noto_Sans({
    subsets: ["latin"],
    weight: "500"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${noto_sansFont.className} flex flex-row antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
